metadata_file: '/home/mcgaugheyd/git/ipsc_rpe_atac/metadata.csv'
bwa_genome: '/fdb/bwa/indexes/hg19.fa'
bwa_version: 'bwa/0.7.17'
genome: '/fdb/genome/hg19/hg19.fa'
homer_hg19: '/data/mcgaugheyd/genomes/hg19/hg19.fa'
bwa_genome_sizes: '/data/genome/chrom.sizes/hg19/chrom.sizes'
samtools_version: 'samtools/1.6'
picard_version:  'picard/2.9.2'
macs2_version: 'macs/2.1.1.20160309'
bedtools_version: 'bedtools/2.27.1'
deeptools_version: 'deeptools/3.1.3'
mosdepth_version: 'mosdepth/0.2.0'
meme_version: 'meme/4.12.0'
downsamples_reads: 20000000
motif_bootstrap_num: 2
rgt_version: 'rgt/0.11.8'
gtf_file: '/data/mcgaugheyd/genomes/1000G_phase2_GRCh37/gencode.v28lift37.basic.annotation.gtf.gz'
gtf_metadata: '/data/mcgaugheyd/genomes/1000G_phase2_GRCh37/gencode.v28lift37.metadata.HGNC.gz'
diff_expression_value: 1
pandoc_version: 'pandoc/2.1.1'
homer_version: 'homer/4.10.1'
diff_expression_csv: '/home/mcgaugheyd/git/ipsc_rpe_RNA-seq/data/RPE_vs_iPSC.results.csv'
R_version: 'R/3.5.0'
msCentipede_version: 'mscentipede/1.0'
peak_comparison_pair: ['GFP_ATAC-Seq__not__IPSC_ATAC-Seq','GFP_ATAC-Seq__not__RFP_ATAC-Seq', 'RFP_ATAC-Seq__not__IPSC_ATAC-Seq']
homer_version: 'homer/4.10.1'
chunks: ['xaa','xab','xac','xad','xae','xaf','xag','xah','xai','xaj','xak','xal','xam','xan','xao','xap','xaq','xar','xas','xat','xau','xav','xaw','xax','xay','xaz','xba','xbb','xbc','xbd','xbe','xbf','xbg','xbh','xbi','xbj','xbk','xbl','xbm','xbn','xbo','xbp','xbq','xbr','xbs','xbt','xbu','xbv','xbw','xbx','xby','xbz','xca','xcb','xcc','xcd','xce','xcf','xcg','xch','xci','xcj','xck','xcl','xcm','xcn','xco','xcp','xcq','xcr','xcs','xct','xcu','xcv','xcw','xcx','xcy','xcz','xda','xdb','xdc','xdd','xde','xdf','xdg','xdh','xdi','xdj','xdk','xdl','xdm','xdn','xdo','xdp','xdq','xdr','xds','xdt','xdu','xdv','xdw','xdx','xdy','xdz','xea','xeb','xec','xed','xee']
