metadata_file: '/home/mcgaugheyd/git/ipsc_rpe_atac/metadata.csv'
bwa_genome: '/data/mcgaugheyd/genomes/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
bwa_version: 'bwa/0.7.12'
bwa_genome_sizes: '/data/mcgaugheyd/genomes/1000G_phase2_GRCh37/GRCh37_gatk_order.genome'
samtools_version: 'samtools/1.6'
picard_version:  'picard/2.9.2'
macs2_version: 'macs/2.1.1.20160309'
bedtools_version: 'bedtools/2.27.1'
deeptools_version: 'deeptools/3.0.1'
mosdepth_version: 'mosdepth/0.2.0'
meme_version: 'meme/4.12.0'
master_meme_motif_file: '/data/mcgaugheyd/motifs/meme_motifs/M6410_1.02.meme'
motif_bootstrap_num: 100
gtf_file: '/data/mcgaugheyd/genomes/1000G_phase2_GRCh37/gencode.v28lift37.basic.annotation.gtf.gz'
